# Generated by Django 2.2.6 on 2020-04-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='请输入作品标题', max_length=30),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.CharField(max_length=80, verbose_name='在这里写作品的简介'),
        ),
    ]
